import XCTest

@testable import AgentCLIKit

final class AgentCLIKitPublicContractTests: XCTestCase {
    func testHostFacingTypesRemainSendable() {
        assertSendable(AgentCLIError.self)
        assertSendable(AgentDiagnosticEvent.self)
        assertSendable(AgentActivityEvent.self)
        assertSendable(AgentContextCompactionEvent.self)
        assertSendable(AgentContextCompactionPhase.self)
        assertSendable(AgentSessionMetadataEvent.self)
        assertSendable(AgentEventEnvelope.self)
        assertSendable(AgentEventSubscription.self)
        assertSendable(AgentCollaborationMode.self)
        assertSendable(AgentSpeedMode.self)
        assertSendable(AgentCollaborationModeEvent.self)
        assertSendable(AgentRuntimeStatus.self)
        assertSendable(AgentRuntimeReconfigureResult.self)
        assertSendable(AgentInteractionRecord.self)
        assertSendable(AgentPendingAction.self)
        assertSendable(AgentProviderAdapterSet.self)
        assertSendable(AgentProviderSessionActionRouter.self)
        assertSendable(AgentProviderOutputContext.self)
        assertSendable(AgentProviderInputContext.self)
        assertSendable(AgentProviderRuntimeContext.self)
        assertSendable(AgentProviderInterruptContext.self)
        assertSendable(AgentProviderReconfigureContext.self)
        assertSendable(AgentProviderReconfigureResult.self)
        assertSendable(AgentProviderRuntimeEvent.self)
        assertSendable(AgentProjectTrustStatus.self)
        assertSendable(DefaultAgentProjectTrustService.self)
        assertSendable(AgentProviderInstallationState.self)
        assertSendable(AgentModelOption.self)
        assertSendable(AgentProviderStatus.self)
        assertSendable(StaticAgentProviderEnablementSource.self)
        assertSendable(StaticAgentProviderCapabilitySource.self)
        assertSendable(DefaultAgentProviderCapabilitySource.self)
        assertSendable(CodexProviderCapabilitySource.self)
        assertSendable(DefaultCodexFeatureSupportChecker.self)
        assertSendable(DefaultAgentProviderExecutableResolver.self)
        assertSendable(StaticAgentModelOptionSource.self)
        assertSendable(DefaultAgentModelOptionSource.self)
        assertSendable(DefaultAgentProviderDiscoveryService.self)
        assertSendable(CodexConfig.self)
        assertSendable(CodexConfigSnapshot.self)
        assertSendable(CodexMCPServerConfig.self)
        assertSendable(CodexAuthReadiness.self)
        assertSendable(CodexAuthProbe.self)
        assertSendable(CodexAppServerModelOptionSource.self)
        assertSendable(ClaudeProviderAdapter.Configuration.self)
        assertSendable(MainActorClaudeHookDecisionProvider.self)
    }

    private func assertSendable<T: Sendable>(_ type: T.Type) {}
}
